blank_issues_enabled: false
contact_links:
  - name: 🔒 Security Vulnerability
    url: ../../SECURITY.md
    about: Please report security vulnerabilities through our security policy
  - name: 💬 GitHub Discussions
    url: https://github.com/wagtail-ai/wag-tail-ai-gateway/discussions
    about: Ask questions and discuss with the community
  - name: 📖 Documentation
    url: ../../README.md
    about: Check our comprehensive documentation