# OSS Edition Configuration
admin:
  api_key: YOUR_ADMIN_API_KEY_HERE
user_api_key: demo-key-for-testing

# Security thresholds for content filtering
security:
  enable_pii_detection: true
  enable_code_detection: true
  max_prompt_length: 10000
  thresholds:
    attack: 0.79
    jailbreak: 0.79
    offensive: 0.81
    sensitive: 0.80
    spam: 0.95
    pii: 0.85

# Rate limiting (requires database)
rate_limiting:
  enabled: false  # Set to true if using PostgreSQL
database:
  host: localhost
  port: 5432
  username: eddiechui
  password: ""
  database: wag_tail
  pool_size: 10
  max_overflow: 20
  connect_timeout: 30
redis:
  host: localhost
  port: 6379
  db: 1
  decode_responses: true
  connection_pool_size: 50
  max_connections: 100
  socket_timeout: 10
  retry_on_timeout: true
# LLM Provider Configuration
llm:
  model: "mistral"
  provider: "ollama"
  api_url: "http://localhost:11434/api/chat"
  
# Logging Configuration
logging:
  level: "INFO"
  file: "logs/wag_tail_gateway.log"
  max_size_mb: 50
  format: "json"
regex:
  output_block_patterns:
    - "rm -rf /"
    - "DROP TABLE"
    - "<script[^>]*>"
    - "\\bexec\\s*\\("
    - "eval\\s*\\("
    - "system\\s*\\("
    - "\\b(sudo|chmod|chown)\\s+"
    - "\\bcurl\\s+.*\\|\\s*(bash|sh)"
    - "\\b(nc|netcat)\\s+.*-e"
